# Generated by Django 5.2.11 on 2026-02-06 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('standard', 'Standard'), ('enterprise', 'Enterprise'), ('pilot', 'Pilot')], default='standard', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab',
                'verbose_name_plural': 'Labs',
                'db_table': 'labs',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='screening.lab')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=100)),
                ('name_encrypted', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='screening.lab')),
                ('referring_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='screening.doctor')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'unique_together': {('patient_id',)},
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(default='screening', max_length=50)),
                ('consent_text', models.TextField()),
                ('consented_by', models.CharField(max_length=255)),
                ('consent_method', models.CharField(choices=[('verbal', 'Verbal'), ('written', 'Written'), ('electronic', 'Electronic')], default='verbal', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('consented_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='screening.patient')),
            ],
            options={
                'db_table': 'consents',
                'ordering': ['-consented_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='consents_patient_c7c376_idx')],
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_by', models.CharField(max_length=255)),
                ('risk_class', models.IntegerField(choices=[(1, 'Normal'), (2, 'Borderline'), (3, 'Deficient')])),
                ('label_text', models.CharField(max_length=50)),
                ('probabilities', models.JSONField()),
                ('rules_fired', models.JSONField(default=list)),
                ('cbc_snapshot', models.JSONField()),
                ('indices', models.JSONField(default=dict)),
                ('model_version', models.CharField(max_length=50)),
                ('model_artifact_hash', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_hash', models.CharField(max_length=64)),
                ('screening_hash', models.CharField(max_length=64)),
                ('consent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings', to='screening.doctor')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='screening.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='screening.patient')),
            ],
            options={
                'db_table': 'screenings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lab', '-created_at'], name='screenings_lab_id_6cec73_idx'), models.Index(fields=['doctor', '-created_at'], name='screenings_doctor__496300_idx'), models.Index(fields=['patient', '-created_at'], name='screenings_patient_c559e3_idx')],
            },
        ),
    ]
