# Generated by Django 5.2.11 on 2026-02-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screening", "0005_alter_patient_encrypted_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="screening",
            name="narrative",
            field=models.TextField(blank=True, default=""),
        ),
    ]
