/**
 * Pure helpers for rendering the four rule-based clinical workflow modules
 * (iron deficiency, beta-thalassemia trait, macrocytic / megaloblastic
 * pattern, composite anemia subtype) in both the on-screen ResultPanel
 * and the downloadable PDF.
 *
 * Lives in its own file (no jspdf, no React) so the helpers are testable
 * under Jest's default jsdom environment without polyfilling TextEncoder.
 *
 * Source of truth for the underlying rule logic is the backend module
 * apps.screening.clinical_rules — keep the keys here in sync with the
 * reasoning codes that module emits.
 */

export const MODULE_LABEL = {
  iron_deficiency: "Iron Deficiency",
  thalassemia_trait: "Beta-Thalassemia Trait",
  macrocytic_anemia: "Macrocytic / Megaloblastic Pattern",
  anemia_subtype: "Anemia Subtype",
};

export const REASONING_LABEL = {
  microcytic_hypochromic_anemia: "microcytic + hypochromic + low Hb",
  mentzer_gt_13_ida_favored_over_btt: "Mentzer > 13 (favors IDA over BTT)",
  green_king_gt_65_ida_favored_over_btt: "Green-King > 65 (favors IDA over BTT)",
  anisocytosis_with_microcytosis: "elevated RDW with microcytosis",
  low_hb_with_low_normal_mcv: "low Hb with low / borderline MCV",
  mentzer_lt_13_btt_suspected: "Mentzer < 13 (BTT pattern)",
  shine_lal_lt_1530_btt_suspected: "Shine-Lal < 1530 (BTT pattern)",
  microcytic_high_rbc_btt_pattern: "microcytic with normal / high RBC count",
  microcytic_uniform_cells_btt_pattern: "microcytic with uniform cell size (low RDW)",
  england_fraser_negative_btt_suspected: "England-Fraser index < 0",
  macrocytic_mcv_gt_100: "MCV > 100 (overt macrocytosis)",
  borderline_macrocytic_with_anisocytosis: "MCV > 95 with elevated RDW",
  macrocytic_hyperchromic_pattern: "MCV > 95 with high MCH",
  possible_megaloblastic_pancytopenia: "anemia + low platelets + low WBC",
  not_microcytic: "not microcytic — module skipped",
  microcytic_but_no_btt_indicators: "microcytic but no BTT indicators",
  insufficient_data: "insufficient CBC data",
};

export const CONFIDENCE_PILL = {
  high: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300 border-red-200 dark:border-red-800",
  medium: "bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300 border-amber-200 dark:border-amber-800",
  low: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300 border-slate-200 dark:border-slate-700",
};

export const formatReasoning = (codes) =>
  (codes || [])
    .map((c) => REASONING_LABEL[c] || c.replace(/_/g, " "))
    .join("; ");

// ── Patient PDF Disclosure Spec — patient-facing translations ────────────
//
// These maps are used ONLY by the spec_v1 patient PDF template — the
// on-screen ResultPanel keeps the clinician-facing labels above so the
// pathologist still sees "Mentzer > 13 (favors IDA over BTT)" in the
// browser.  The patient-facing copy here was authored as the counsel-
// review draft per the April 2026 Patient PDF Disclosure Specification
// (§D — card translations).
export const PATIENT_MODULE_TITLE = {
  iron_deficiency: "Iron-related follow-up testing may be considered",
  thalassemia_trait: "Hemoglobin pattern follow-up testing may be considered",
  macrocytic_anemia: "Vitamin B12 and folate follow-up testing may be considered",
  anemia_subtype: "Anemia follow-up testing may be considered",
  // Reserved for the B12 ML output if it is ever surfaced as a
  // workflow card on the patient PDF (currently rendered as the
  // primary screening result, not as a workflow card).
  b12_reflex_testing: "Vitamin B12 follow-up testing may be considered",
};

export const PATIENT_CONFIDENCE_LABEL = {
  high: "Stronger workflow signal",
  medium: "Moderate workflow signal",
  low: "Weaker workflow signal",
};

export const PATIENT_REASONING_LABEL = {
  microcytic_hypochromic_anemia: "Red cell pattern suggesting iron-related investigation",
  mentzer_gt_13_ida_favored_over_btt: "Cell-size pattern suggesting iron-related follow-up",
  green_king_gt_65_ida_favored_over_btt: "Cell-size pattern suggesting iron-related follow-up",
  anisocytosis_with_microcytosis: "Variation in red cell size with smaller cells",
  low_hb_with_low_normal_mcv: "Lower hemoglobin with red cell size pattern",
  mentzer_lt_13_btt_suspected: "Red cell pattern flag (hemoglobin types)",
  shine_lal_lt_1530_btt_suspected: "Red cell pattern flag (hemoglobin types)",
  microcytic_high_rbc_btt_pattern: "Red cell count pattern flag",
  microcytic_uniform_cells_btt_pattern: "Red cell pattern flag",
  england_fraser_negative_btt_suspected: "Red cell pattern flag",
  macrocytic_mcv_gt_100: "Larger red cell pattern",
  borderline_macrocytic_with_anisocytosis: "Larger red cell pattern with size variation",
  macrocytic_hyperchromic_pattern: "Larger red cell pattern",
  possible_megaloblastic_pancytopenia: "Combined cell count and red cell pattern",
};

export const PATIENT_SOURCE_LINE = {
  iron_deficiency:
    "Generated by established laboratory rules from clinical hematology literature. " +
    "This is a workflow suggestion only.",
  thalassemia_trait:
    "Generated by established laboratory rules from clinical hematology literature. " +
    "This is a workflow suggestion only.",
  macrocytic_anemia:
    "Generated by established laboratory rules from clinical hematology literature. " +
    "This is a workflow suggestion only.",
  anemia_subtype:
    "Generated by established laboratory rules from clinical hematology literature. " +
    "This is a workflow suggestion only.",
  b12_reflex_testing:
    "Generated by AI software based on patterns in your CBC. " +
    "This is a workflow suggestion only, not a measurement of vitamin B12 in your blood.",
};

export const PATIENT_EMPTY_STATE_TEXT =
  "Based on your CBC results, the software did not generate any additional " +
  "workflow recommendations at this time. This does not mean you have no " +
  "health concerns — please discuss your full results with your doctor as " +
  "you would for any laboratory test.";

export const PATIENT_MACROCYTIC_FOOTNOTE =
  "Note: in many Indian patients, vitamin B12 deficiency does not cause " +
  "the changes this rule looks for. The vitamin B12 workflow recommendation " +
  "above (if shown) is a more reliable indicator from this software.";

/** Render a missing-value placeholder.  Counsel-spec wants ``[TBD]``
 * visible (not hidden) so the per-lab readiness audit can see what's
 * unfilled.  Treat all-whitespace as empty. */
export const tbd = (value) => {
  if (value === null || value === undefined) return "[TBD]";
  const s = String(value).trim();
  return s === "" ? "[TBD]" : s;
};

/** True iff every truly-required disclosure value is present.  Used by
 * the operations runbook check; the renderer itself fails-soft to
 * ``[TBD]`` regardless of this. */
export const disclosureConfigComplete = (config) => {
  if (!config) return false;
  const required = [
    "dpo_email",
    "cdsco_license_number",
    "grievance_email",
    "privacy_notice_url",
    "pathologist_name",
    "pathologist_registration",
    "pathologist_qualification",
    "pathologist_designation",
  ];
  return required.every((k) => {
    const v = config[k];
    return typeof v === "string" && v.trim() !== "";
  });
};

/** Patient-facing card row builder for spec_v1 PDF.  Returns null when
 * the module did not flag (so the empty-state branch in the renderer
 * stays clean). */
export const patientModuleCard = (moduleKey, payload) => {
  if (moduleKey === "anemia_subtype") {
    if (payload?.anemic !== true || !payload.suspected_subtype) return null;
    return {
      title: PATIENT_MODULE_TITLE.anemia_subtype,
      confidenceLabel: "",  // composite module — no single confidence tier
      reasoning: [PATIENT_REASONING_LABEL[payload.suspected_subtype]
        || "Combined CBC pattern flag"],
      source: PATIENT_SOURCE_LINE.anemia_subtype,
      moduleKey,
    };
  }
  if (!payload || payload.flag !== true) return null;
  const reasoning = (payload.reasoning || []).map(
    (c) => PATIENT_REASONING_LABEL[c] || "CBC pattern flag",
  );
  // De-duplicate — multiple internal codes may map to the same patient
  // chip and the patient doesn't benefit from repetition.
  const dedup = Array.from(new Set(reasoning));
  return {
    title: PATIENT_MODULE_TITLE[moduleKey] || moduleKey.replace(/_/g, " "),
    confidenceLabel: PATIENT_CONFIDENCE_LABEL[payload.confidence] || "",
    reasoning: dedup,
    source: PATIENT_SOURCE_LINE[moduleKey] || PATIENT_SOURCE_LINE.iron_deficiency,
    moduleKey,
  };
};

/**
 * Convert one module's payload into a tabular row [label, confidence,
 * reasoning, recommendation], or null if the module did not flag.
 * The composite anemia_subtype module reports under different keys
 * (`anemic`, `suspected_subtype`) so it has its own branch.
 */
export const moduleCells = (moduleKey, payload) => {
  if (moduleKey === "anemia_subtype") {
    if (payload?.anemic !== true || !payload.suspected_subtype) return null;
    const subtype = payload.suspected_subtype.replace(/_/g, " ");
    return [
      MODULE_LABEL[moduleKey],
      "—",
      `suspected: ${subtype}`,
      payload.recommendation || "",
    ];
  }
  if (!payload || payload.flag !== true) return null;
  return [
    MODULE_LABEL[moduleKey] || moduleKey,
    payload.confidence || "—",
    formatReasoning(payload.reasoning),
    payload.recommendation || "",
  ];
};

/**
 * Same data as `moduleCells` but shaped for React rendering rather
 * than table cells.  Returns an array of objects with `key`, `label`,
 * `confidence`, `reasoning` (raw codes), and `recommendation`.  Used by
 * ResultPanel.
 */
export const flaggedModules = (clinicalRules) => {
  if (!clinicalRules) return [];
  const out = [];
  for (const key of ["iron_deficiency", "thalassemia_trait", "macrocytic_anemia"]) {
    const m = clinicalRules[key];
    if (m && m.flag === true) {
      out.push({
        key,
        label: MODULE_LABEL[key],
        confidence: m.confidence,
        reasoning: m.reasoning || [],
        recommendation: m.recommendation,
      });
    }
  }
  const subtype = clinicalRules.anemia_subtype;
  if (subtype && subtype.anemic === true && subtype.suspected_subtype) {
    out.push({
      key: "anemia_subtype",
      label: MODULE_LABEL.anemia_subtype,
      confidence: null,
      reasoning: [`suspected: ${subtype.suspected_subtype.replace(/_/g, " ")}`],
      recommendation: subtype.recommendation,
    });
  }
  return out;
};

/**
 * Build the ``result`` object the PDF generator and ResultPanel expect
 * from a stored screening record.  Pure data transform — kept out of
 * generateReport.js so tests don't have to load jspdf.
 */
export function buildResultFromScreening(screening) {
  const riskClass = screening.risk_class;
  let recommendation;
  if (riskClass === 3) {
    recommendation = "Serum B12 measurement recommended. Clinical correlation advised.";
  } else if (riskClass === 2) {
    recommendation = "Consider serum B12 measurement if clinically indicated.";
  } else {
    recommendation = "B12 deficiency unlikely based on CBC parameters.";
  }

  return {
    label: riskClass,
    probabilities: screening.probabilities,
    indices: screening.indices,
    interpretation: (screening.rules_fired || []).join(", "),
    recommendation,
    // Both casings tolerated — snake_case from the GET serializer,
    // camelCase from the live predict response.
    clinicalRules: screening.clinical_rules || screening.clinicalRules || null,
    cbcSnapshot: screening.cbc_snapshot || screening.cbcSnapshot || null,
    // Patient PDF Disclosure Spec — Option A gate.  Defaults to false
    // when the field is absent (legacy responses, FHIR-bypass reads,
    // anything pre-Option-A) so a missing flag fails *closed* — the
    // patient PDF withholds the Workflow Recommendations section.  Only
    // an explicit ``true`` from the backend opens the gate.
    labWorkflowRecsEnabled: Boolean(
      screening.lab_workflow_recs_enabled
        ?? screening.labWorkflowRecsEnabled
        ?? false,
    ),
    // Manufacturer + per-lab disclosure config bundle for spec_v1
    // template (Block A header, Block E pathologist sign-off, Block F
    // footer).  Tolerated under both casings; falls back to ``null`` so
    // the renderer's [TBD] fallback path triggers cleanly.
    disclosureConfig:
      screening.disclosure_config || screening.disclosureConfig || null,
  };
}
